motors:
  motor_id:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
  offsets:
    - 169.189
    - 91.934
    - 134.824
    - 184.482
    - 136.318
    - 165.498
    - 179.736
    - 188.174
    - 182.988
    - 134.033
    - 174.463
    - 226.494
    - 193.184
    - 170.771
  negations:
    - 1
    - -1
    - 1
    - -1
    - 1
    - 1
    - -1
    - 1
    - 1
    - 1
    - 1
    - 1
    - -1
    - -1